### PR TITLE
Update to agent 0.10

### PR DESCRIPTION
**Pull request by guizmaii**

### CODE REVIEW

**Comment by tylerbenson** [comment]
Sorry to add the extra config mess... we do this so it's not a forced upgrade for something that is relatively new.  Hopefully these will get enabled by default in the next release.  In your experience, is the netty and akkahttp instrumentation working well?

**Comment by guizmaii** [comment]
Hi @tylerbenson,

First, thanks to take time to follow this project !

> Sorry to add the extra config mess... we do this so it's not a forced upgrade for something that is relatively new.

No problem. I understand why you're doing this. 
It's great to see that you add quickly new interesting things like Akka-HTTP and Netty support ! 👍 

> In your experience, is the netty and akkahttp instrumentation working well?

We have a Lagom project composed of several services, including one being what Lagom names a "PlayScala" project (Play 2.6 project). Everything is Akka-HTTP based.
Since the Datadog APM v0.9.0 (the first we've added in our project), the "PlayScala" service appears in the Datadog dashboard.
I've added the v0.10.0 version with the `-Ddd.integration.akka-http.enabled=true` flag since the 29 June but nothing new appeared in our dashboard 😕
I still don't have my Lagom services monitored. 😕

**Comment by realark** [comment]
Hi @guizmaii is it possible for you to collect debug logs from your service? I can take a look and see if there's anything wrong with the akka-http integration.

Instructions for enabling here: https://docs.datadoghq.com/tracing/setup/java/#debugging

Logs will appear in stdout/stderr.

**Comment by guizmaii** [comment]
Hi @realark,

I activated the debug mode since about 10 minutes. Can you access my logs in Datadog ? Could be simpler for you to see what is happening.

Jules

**Comment by realark** [comment]
Thankjs @guizmaii. I actually can't access those logs (they aren't reported). Is it possible for you to capture stdout/stderr and send me a log file?

**Comment by guizmaii** [comment]
How can I send you the file ? Do you have an email ? Twitter ? Other ?

**Comment by guizmaii** [comment]
Sent 😉

**Comment by tylerbenson** [comment]
@guizmaii you can also ping either of us on datadog slack: http://chat.datadoghq.com/

That's often the easiest place for adhoc support questions.

**Comment by guizmaii** [comment]
As said by email, without Lightbend Telemetry agent, your APM does work well with Lagom.

Thanks for your help. :)

**Pull request merged**
