### PR TITLE
bump agent version to support JDK 16/17

### PR DESCRIPTION
**Pull request by keirlawson**

### CODE REVIEW

**Comment by guizmaii** [comment]
@keirlawson Thanks for your contribution ❤️

Do you know that you can override this version in your sbt config by adding: `datadogApmVersion  := "0.100.0"`?

**Comment by keirlawson** [comment]
ah I hadn't spotted that, thanks!

**Comment by guizmaii** [comment]
@keirlawson Reading the DD agent changelog (https://github.com/DataDog/dd-trace-java/releases/tag/v0.100.0), I don't see any mention of JDK16/17. Where can I find more information about this, please?

**Comment by keirlawson** [comment]
its in 0.75 I believe, but I figured whilst I was bumping the version may as well go to latest

**Comment by keirlawson** [comment]
stale

**Pull request closed without merging**
